apiVersion: v1
kind: Pod
metadata:
  name: qos-demo
  labels:
    env: prod
    #  namespace: qos-example.
spec:
  containers:
  - name: qos-demo-ctr
    image: nginx
    resources:
      limits:
        memory: "200Mi"
        cpu: "700m"
      requests:
        memory: "200Mi"
        cpu: "700m"

    resources:
      limit:
        memory: "100Mi"
        cpu: "100m"
      requests: 
        memory 
