apiVersion: v1
kind: Pod
metadata:
  name: book-front
  labels:
    app: mysql
    managed-by: db
    version: "10"
    component: backend
    part-of: Library
    instance: may2025
    env: dev
    client: xyz
spec:
  containers:
    - name: ngnix-container
      image: ngnix:latest

-------------

apiVersion: v1
kind: Pod
metadata:
  name: book-front
  labels:
    app: mysql
    managed-by: db
    version: "10"
    component: backend
    part-of: Library
    instance: may2025
    env: dev
    client: xyz
spec:
  containers:
    - name: gaurav-container
      image: coolgourav147/nginx-custom
      env: 
        - name: myname
          value: gaurav
        - name: city
          value: jaipur
          